app/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from extensions import db
from mixin import CRUDMixin
from config import Configuration as CFG

from werkzeug.security import generate_password_hash, check_password_hash


class Cards(db.Model, CRUDMixin):
    card_number = db.Column(db.String)
    pin_code = db.Column(db.String)
    amount = db.Column(db.Float)
    is_blocked = db.Column(db.Boolean)
    login_attempts = db.Column(db.Integer)

    def __init__(self, **kwargs):
        kwargs["pin_code"] = generate_password_hash(kwargs["pin_code"])
        super(Cards, self).__init__(**kwargs)

    def check_password(self, password):
        return check_password_hash(self.pin_code, password)


class Operations(db.Model, CRUDMixin):
    card_id = db.Column(db.Integer, db.ForeignKey('cards.id'))
    operation_type = db.Column(db.String)
    amount = db.Column(db.Float)

app/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Flask
from extensions import db
from views import main

app = Flask(__name__, template_folder='../templates',
            static_folder='../static')
app.config.from_object('config.Configuration')

# init db
db.app = app
db.init_app(app)


# register blueprint
app.register_blueprint(main, url_prefix='/')

app/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from models import Cards, Operations
from utils import print_obj, get_current_time
from flask import Blueprint, redirect, request, Response, render_template, url_for, g, session, flash
from extensions import db

import datetime

main = Blueprint('main', 'main')


@main.before_request
def before_request():
    if "card" not in session and request.endpoint not in('main.login', 'main.test', 'main.error_page'):
        return redirect(url_for("main.login"))



@main.route('/', methods = ["GET", "POST"])
def login():
    session.clear()
    if request.method == "POST" and request.form:
        card_number = request.form["creditcard"]
        card = Cards.query.filter_by(card_number=card_number, is_blocked = False).first()
        if not card:
            return redirect(url_for("main.error_page", message = "Can't find valid card"))
        session["card"] = card.id
        return redirect(url_for("main.pin_enter"))
    session.clear()
    return render_template("login.html")


@main.route('pin/', methods = ["GET", "POST"])
def pin_enter():
    card = Cards.get(session["card"])
    print card
    if request.method == "POST":
        if not card.check_password(request.form["pin"]):
            if card.login_attempts >= 4:
                card.update(is_blocked=True)
                return redirect(url_for("main.error_page", message ="Card Blocked"))
            la = card.login_attempts + 1
            card.update(login_attempts=la)
            return redirect(url_for("main.pin_enter"))
        else:
            card.update(login_attempts=0)
            return redirect(url_for("main.menu"))
    return render_template("pin.html")


@main.route('menu/')
def menu():
    return render_template("menu.html")


@main.route('balance/')
def balance():
    card = Cards.get(session["card"])
    current_date = get_current_time()
    return render_template("balance.html", card=card, current_date=current_date)


@main.route('get_money/', methods = ["GET", "POST"])
def get_money():
    card = Cards.get(session["card"])
    if request.method == "POST":
        money = float(request.form["money"])
        if card.amount <= money:
            return redirect(url_for("main.error_page", message="Not enough money"))
        new_sum = card.amount - money
        card.update(amount=new_sum)
        Operations.create(operation_type="get_money",amount=money, card_id=card.id)
        session["money"] = money
        return redirect(url_for("main.operation_results"))
    return render_template("money.html")


@main.route('operation_results/')
def operation_results():
    card = Cards.get(session["card"])
    money = session.pop("money")
    current_date = get_current_time()
    return render_template("operation_results.html", card=card, current_date=current_date, money=money)


@main.route('error/<message>')
def error_page(message):
    return render_template('404.html', message=message), 404


@main.route('create_test_data/')
def test():
    Cards.create(
        pin_code='1111', 
        card_number='1111-1111-1111-1111', 
        amount=2568.10, 
        is_blocked=False, 
        login_attempts =0
    )
    Cards.create(
        pin_code='1234', 
        card_number='2222-5555-8888-8888', 
        amount=500.10, 
        is_blocked=False, 
        login_attempts =0
    )
    return 'ok'

templates/balance.html
{% extends "layout.html" %}
{% block body %}
	<dt>Card number:
	<dd></dd><label for="amount">{{card.card_number}}</label>
	<dt>Money amount:
	<dd></dd><label for="amount">{{card.amount}}</label>
	<dt>Date:
	<dd></dd><label for="date">{{current_date}}</label>
	<a href="{{ url_for('main.menu') }}" class="btn btn-default">Back</a>
	<a href="{{ url_for('main.login') }}" class="btn btn-default">Exit</a>
{% endblock%}

templates/layout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    	<link rel="stylesheet" href="/static/css/bootstrap.css">
    	<link rel="stylesheet" href="/static/css/bootstrap-responsive.css">
    </head>
    <body>
        <div class="row">
            <div class="span4 offset6" style="border: 1px solid #ccc; padding-left: 10px;padding-top: 10px;padding-bottom: 20px;">
                {% block body %}
                {% endblock%}
            </div>
        </div>
    </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
<form action="" method=post>
    <dt>Enter credit card number:
    <dd><input type="text" name=creditcard id=cred maxlength = "19">
    <dd><input class="btn btn-default" type="submit" value="Enter">
    <input class="btn btn-default" type="reset" value="Reset">
</form>

<script type="text/javascript" src="/static/js/jquery-2.1.0.min.js"></script>
<script type="text/javascript">
    $('#cred').keyup(function()
    {
        $(this).val(function(i, v)
        {
            var v = v.replace(/[^\d]/g, '').match(/.{1,4}/g);
            return v ? v.join('-') : '';
        });
    });
</script>
{% endblock %}

templates/menu.html
{% extends "layout.html" %}
{% block body %}
<a href="{{ url_for('main.balance') }}" class="btn btn-default">Balance</a>
<br>
<a href="{{ url_for('main.get_money') }}" class="btn btn-default">Get money</a>
<br>
<a href="{{ url_for('main.login') }}" class="btn btn-default">Exit</a>
{% endblock%}

templates/money.html
{% extends "layout.html" %}
{% block body %}
<form action="" method=post>
    <dt>Enter sum:
    <dd><input type="number" name="money" min="10.00" step="10.00" max="2500">
    <dd><input class="btn btn-default" type="submit" value="Enter">
	<input  class="btn btn-default" type="reset" value="Reset">
</form>
<a href="{{ url_for('main.menu') }}" class="btn btn-default">Back</a>
<a href="{{ url_for('main.login') }}" class="btn btn-default">Exit</a>
{% endblock%}

templates/operation_results.html
{% extends "layout.html" %}
{% block body %}
	<dt>Card number:
	<label for="amount">{{card.card_number}}</label>
	<dt>You've got sum:
	<dd><label for="amount">{{money}}</label>
	<dt>Money amount left:
	<dd><label for="date">{{card.amount}}</label>
	<dt>Date:
	<dd><label for="date">{{current_date}}</label>
	<br>
	<a href="{{ url_for('main.get_money') }}" class="btn btn-default">Back</a>
	<a href="{{ url_for('main.login') }}" class="btn btn-default">Exit</a>
{% endblock%}

templates/pin.html
{% extends "layout.html" %}
{% block body %}
<form action="" method=post>
    <dt>Enter pin:
    <dd><input type="password" name=pin  id=pin maxlength="4" pattern="[0-9]*" 
    	oninvalid="setCustomValidity('Please use only numbers')"
    	onchange="try{setCustomValidity('')}catch(e){}"/>
    <dd><input class="btn btn-default" type="submit" value="Enter">
	<input type="reset" value="Reset">
</form>

<a href="{{ url_for('main.login') }}" class="btn btn-default">Exit</a>

<script type="text/javascript" src="/static/js/jquery-2.1.0.min.js"></script>
<script type="text/javascript">
    $('#pin').keyup(function()
    {
        $(this).val(function(i, v)
        {
            var v = v.replace(/[^\d]/g, '');
            return v ? v : '';
        });
    });
</script>
{% endblock%}